### ISSUE TITLE
「相談の手順」リンク切れ？

### ISSUE THREAD

**Issue by Yfuruchin** [civictechzenchiba/covid19-chiba#112]
どうもです、北海道版の中の人です。構築お疲れさまでした！
さて、一点リンク切れがあるようです、ご確認ください

## 起こっている問題 / Occurred problem
- 「相談の手順」のリンク先が404
![image](https://user-images.githubusercontent.com/4961152/77030357-a9781a00-69e1-11ea-9309-d5c40a47778f.png)

https://www.pref.chiba.lg.jp/kenfuku/kansenshou/singata-korona-soudan.html#meyasu

## 期待する見せ方・挙動 / Expected behavior
- 正しいリンクに更新がよいかと
（正しいリンク先が見つけれませんでした、すみません）

**Comment by yamanoku** [comment]
代替、これですかね
https://www.pref.chiba.lg.jp/shippei/kansenshou/2019-ncov.html#an1

**Comment by Nekoya3** [comment]
https://www.pref.chiba.lg.jp/kenfuku/kansenshou/corona-soudancenter.html#meyasu

こちらがおなじページのようだったのでこちらに変更しています！
