### ISSUE TITLE
最新のお知らせ欄の制限

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#118]
## 改善詳細 / Improve details
- 最新のお知らせ欄が長いのでグラフが見えなくなっている。
## スクリーンショット / Screenshot
<img width="1440" alt="スクリーンショット 2020-03-20 10 49 10" src="https://user-images.githubusercontent.com/19554609/77129981-69746e00-6a99-11ea-806a-acad17b7b4c0.png">

## 期待する見せ方・挙動 / Expected behavior
- 最新のお知らせ欄を2列にする
-  保留中→（read more　で県のサイトにリンクを貼る）
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nekakoshi** [comment]
最新の定義をしてあげてください。
以下のいずれかになるかと思います。
- 何件までの表示(最新の５件)
- 何日までの表示(5日前までの情報を表示)

お知らせページを別途作成した方が良さそうかと思います。
別タスクでお知らせページの作成を作り、
その後こちらのタスクを実施した方が綺麗にできそうですね。

**Comment by MiyukiShirasawa** [comment]
何件までの表示(最新の５件)がいいですね！
> お知らせページを別途作成した方が良さそうかと思います。
別タスクでお知らせページの作成を作り、
その後こちらのタスクを実施した方が綺麗にできそうですね。

issue作成した方がいいですね。
