### ISSUE TITLE
AboutページのHTML構文エラーの解消、見出し修正

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#195]
## 起こっている問題 / Occurred problem
- https://covid19.civictech.chiba.jp/about
- 構文エラー
  - pタグの中にulがある
- 見出し修正
  - 「当サイトについて」がh2に対してそれ以下の「ブラウザ環境について」もh2で階層構造が同列

### 構文エラー
<img width="497" alt="スクリーンショット 2020-04-04 18 23 45" src="https://user-images.githubusercontent.com/1996642/78423469-77351080-76a1-11ea-8a46-d2a9625b1a58.png">

### 見出し
<img width="346" alt="スクリーンショット 2020-04-04 18 50 32" src="https://user-images.githubusercontent.com/1996642/78423967-2e7f5680-76a5-11ea-91b3-8469f0660c89.png">

## 期待する見せ方・挙動 / Expected behavior
- 構文エラーの対応
- 見出しを正しい階層構造にする

### 対応参考
- https://github.com/tokyo-metropolitan-gov/covid19/pull/741
- https://github.com/tokyo-metropolitan-gov/covid19/pull/1908

## 動作環境・ブラウザ / Environment
すべて

**Comment by stamefusa** [comment]
こちら https://github.com/civictechzenchiba/covid19-chiba/pull/230 にて対応しましたのでご確認いただければと思います。
ただ、`tokyo-metropolitan-gov/covid19` の方ではStaticCardが作成され、そちらを利用しているようです。
https://github.com/tokyo-metropolitan-gov/covid19/pull/916
https://github.com/tokyo-metropolitan-gov/covid19/pull/1642
こちらのリポジトリがどの程度追従するものなのか分からないため、一旦StaticCardは作成せず既存のTextCardの修正に留めています。

**Comment by yamanoku** [comment]
これがマージされたらStaticCard作りましょうか
