### ISSUE TITLE
各グラフのツールチップの内容を凡例の選択と連動させたい

### ISSUE THREAD

**Issue by scraperonce** [civictechzenchiba/covid19-chiba#207]
## 改善詳細 / Improve details
- 検査実施数などのグラフで凡例を選択した際、ツールチップに表示される内容は選択とは無関係に全て表示されている。

## スクリーンショット / Screenshot
<img width="554" alt="issue" src="https://user-images.githubusercontent.com/389314/78472574-fc3d2a00-7774-11ea-865c-afdbff1abf39.png">

## 期待する見せ方・挙動 / Expected behavior
- できれば選択した凡例のデータのみをツールチップの内容に表示したい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamanoku** [comment]
#202 とも関連しそう
