### ISSUE TITLE
コピーライト表示変更

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#25]
## コピーライトの表示変更
-現在東京都になっている表示を千葉県サイト版へ変更したい

##
<img width="516" alt="スクリーンショット 2020-03-15 14 06 40" src="https://user-images.githubusercontent.com/19554609/76695757-60188980-66c6-11ea-90c5-df762392e450.png">

## 期待する見せ方・挙動 / Expected behavior
 - 1)削除
・Copyright © 2020 Tokyo Metropolitan Government. All Rights Reserved.表記
・Facebookリンク
・Twitterリンク
・Lineリンク
-2)追加
・Data by:千葉県
https://www.pref.chiba.lg.jp/
・Operations by:CivicTechZenChiba
https://sites.google.com/view/civictechzenchiba/

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by resessh** [comment]
やります

**Comment by resessh** [comment]
@MiyukiShirasawa 新しくGithubへのリンクを用意して、コントリビューションしやすいようにしたら良いかなと思ったんですが、どうでしょう？

本家Tokyoはこんな感じです
![image](https://user-images.githubusercontent.com/1481277/76695892-06b15a00-66c8-11ea-899a-60c81c631cfb.png)

**Comment by MiyukiShirasawa** [comment]
Githubリンクアリです〜
