### ISSUE TITLE
グラフ内「陽性者数」の表記を「陽性患者」に変更

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#264]
## 改善詳細 / Improve details
- 検査陽性者の状況の中で、「陽性者数」との表示が現在されているところに「無症状」の場合の入退院すうが含まれていないため、「陽性患者」と表記を変更する必要がある

## スクリーンショット / Screenshot
[プレゼンテーション1.pdf](https://github.com/civictechzenchiba/covid19-chiba/files/4469920/1.pdf)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamanoku** [comment]
こちら対応してみます

**Comment by yamanoku** [comment]
SVGになっているので更新しづらいままになってますね。。。
たしか本家だとHTMLに書き換えてるはずなのでそっちもついでに対応します。
