### ISSUE TITLE
readmeのslack invitation link が無効

### ISSUE THREAD

**Issue by kozayupapa** [civictechzenchiba/covid19-chiba#284]
## 起こっている問題 / Occurred problem
- README.mdのSlackグループインビテーションが無効

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/3196383/79681040-4df3b300-8251-11ea-9415-3561d3e642fe.png)

## 期待する見せ方・挙動 / Expected behavior
- 有効なリンクでSlackに参加できる

## 起こっている問題の再現手段 / Steps to reproduce
1. README.mdにあるリンクをクリック

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by kozayupapa** [comment]
はじめまして　四街道在住です。　千葉の活動に貢献したいと思います。Slackもあるのであれば参加したいと思います。ご確認よろしくお願いいたします

**Comment by yamanoku** [comment]
@kozayupapa 無期限の招待リンク作成しました。こちらからお願いします。
https://join.slack.com/t/civictechzenchiba/shared_invite/zt-dnurg6f9-tta8UTbhd0fP58dFiBzOMQ
READMEの方は改めてPull Request作成します。
