### ISSUE TITLE
最終更新のtime要素が表示されていない

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#32]
## 起こっている問題 / Occurred problem
- 「県内の最新感染動向」の次に設置されている「最終更新」部分の時間が表示されていない
- 「陽性患者数」、「陽性患者の属性」の「最終更新」部分の時間が表示されていない

## スクリーンショット / Screenshot

![スクリーンショット 2020-03-15 15 52 13](https://user-images.githubusercontent.com/1996642/76697013-0c616c80-66d5-11ea-81db-afbe758b2fce.png)

[![Screenshot from Gyazo](https://gyazo.com/d75556bc8710fe6df9a5057453b2b42d/raw)](https://gyazo.com/d75556bc8710fe6df9a5057453b2b42d)

## 期待する見せ方・挙動 / Expected behavior
- エラーなく表示されるようにする

## 起こっている問題の再現手段 / Steps to reproduce
1. TOPページにアクセスする

**Comment by yamanoku** [comment]
ここが空のため
https://github.com/civictechzenchiba/covid19-chiba/blob/c3ec3219a13b91c91d6b3005fb33fa40f2f58186/data/data.json#L1083

**Comment by yamanoku** [comment]
手動更新っぽい？
https://github.com/tokyo-metropolitan-gov/covid19/commit/e5a326e2989b19efc3ce1e99ae6091d0fee41e18

**Comment by smellman** [comment]
#101 で対応します！

**Comment by smellman** [comment]
https://github.com/civictechzenchiba/covid19-chiba-tools/issues/6
related issue残してこちらは一旦closeします！
