### ISSUE TITLE
GoogleAnalyticsの日次情報をSlackに投稿する仕組み作り

### ISSUE THREAD

**Issue by nekakoshi** [civictechzenchiba/covid19-chiba#323]
## 改善詳細 / Improve details

GoogleAnalyticsの共有可能な数字をSlack通知お願い致します。

[Statsbot](https://statsbot.co/) というツールを利用して
GoogleAnalyticsの見せたい項目をSlackに通知することが可能です。
以下の参照URLの内容で進めて頂ければ設定可能かと思います。

参照URL
- https://upd.world/google-analytics-slack-statsbot/

**Comment by MiyukiShirasawa** [comment]
done!!
