### ISSUE TITLE
「当サイトについて」記載内容変更

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#33]
## 掲載内容変更
- サイト内を、千葉県との共業について言及したものに変更

## スクリーンショット / Screenshot
<img width="1156" alt="スクリーンショット 2020-03-15 15 47 01" src="https://user-images.githubusercontent.com/19554609/76697091-e7b9c480-66d5-11ea-99b5-2e925c95abfc.png">

## 期待する見せ方・挙動 / Expected behavior
- 変更前
当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都が開設したものです。

東京都による公式情報と客観的な数値をわかりやすく伝えることで、東京都にお住まいの方や、東京都内に拠点を持つ企業の方、東京都を訪れる方が、現状を把握して適切な対策を取れるようにすることを目的としています。

-変更後
当サイトは、千葉県とCivicTechZenChibaの組織を超えた共業のもと、新型コロナウィルス感染症（COVID-19）における公式情報と客観的な数値をわかりやすく伝え、千葉県にお住まいの方、企業の方、観光に訪れる方が、現状を把握して適切な対策を取ることができるようにすることを目的としています。
開発は、シビックテック 団体CivicTechZenChibaIが行っています。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by potyama** [comment]
対応します
