### ISSUE TITLE
Flowの東京都の情報を千葉県のものに差し替え対応

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#34]
ref #9 

## PC
[![Screenshot from Gyazo](https://gyazo.com/359a2fea178933e86ca98535b728b2bb/raw)](https://gyazo.com/359a2fea178933e86ca98535b728b2bb)

## SP
[![Screenshot from Gyazo](https://gyazo.com/5be57b75f744750da4fbd4fe081d7945/raw)](https://gyazo.com/5be57b75f744750da4fbd4fe081d7945)

**Comment by MiyukiShirasawa** [comment]
リンク先のみ一部修正済

**Comment by resessh** [comment]
今のところ、内容の編集・アップデートの継続が難しそうと判断し、一旦サイドバーからのナビゲーションを消しました。またflowをまとめる機運が発生したら別issue立ててすすめるのが良さそうです
