### ISSUE TITLE
Workerの東京都の情報を千葉県のものに差し替え対応

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#36]
ref: #9, #14 

## 対象
- 事業継続緊急対策（テレワーク）助成金
- 中小企業者等特別相談窓口
- 緊急労働相談ダイヤル
- 新しいワークスタイルや企業活動の東京モデル「スムーズビズ」

が東京都のものなので対象のものがあれば差し替え、なければコメントアウトなどで千葉のものにしておく

## 参考情報
`pref.chiba.lg.jp/keishi/ncov/ncov-index.html` から参考

### 雇用助成
`mhlw.go.jp/stf/newpage_09477.html`

### 相談窓口
`pref.chiba.lg.jp/keisei/singata-koronauirusu-kigyousoudan.html`

**Comment by potyama** [comment]
対応します
