### ISSUE TITLE
forkedSites.mdに千葉県対策サイトを追加する

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#38]
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/forkedSites.md

公開できる段階になったら追加のプルリクエストを作成する

**Comment by MiyukiShirasawa** [comment]
https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?both
https://hackmd.io/@homata/ryHz3P4BI
掲載済

**Comment by yamanoku** [comment]
こちらでも掲載確認できました 🎉 
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md
