### ISSUE TITLE
陽性反応者数の推移のデータ自動更新と表示の変更（データの自動更新後）

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#387]
## 改善詳細 / Improve details
千葉県のデータが公開されるようになったので、下記のURLから自動的に取得するようにする。
https://www.pref.chiba.lg.jp/shippei/press/2019/documents/chiba_corona_data.xlsx

１陽性患者と無症状患者の区分をなくす
→ 無症状病原体保有者の区分を消す、全て陽性患者として処理する
２データ取得方法の変更（自動取得
データ→Excelファイル『感染者数等の詳細データ』の
シート名「新型コロナウイルス感染者数（検査確定日、公表日、7日間平均）」
日付→B列
患者数→C列
のデータを取得

## スクリーンショット / Screenshot

<img width="686" alt="スクリーンショット 2020-06-07 7 40 43" src="https://user-images.githubusercontent.com/19554609/83955863-906d5f80-a892-11ea-8945-84539cf8f9e3.png">

## 期待する見せ方・挙動 / Expected behavior
<img width="757" alt="スクリーンショット 2020-06-07 7 43 44" src="https://user-images.githubusercontent.com/19554609/83955892-daeedc00-a892-11ea-8aa7-e886331f3296.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kozayupapa** [comment]
対応中です

**Comment by kozayupapa** [comment]
@MiyukiShirasawa 
情報として１種類だけになったので積み上げではなく単純な棒グラフとなっています
こちらで問題ないでしょうか？
![image](https://user-images.githubusercontent.com/3196383/84958591-ac95ba00-b138-11ea-9359-595a9ac916e7.png)

![image](https://user-images.githubusercontent.com/3196383/84958698-e23aa300-b138-11ea-9b82-51cb540fe0dd.png)

**Comment by MiyukiShirasawa** [comment]
@kozayupapa ありがとうございます！
大丈夫です！！
