### ISSUE TITLE
検査実施数の自動データ取得

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#390]
## 改善詳細 / Improve details
千葉県がデータ公開を始めたので自動取得を行いたい。
https://www.pref.chiba.lg.jp/shippei/press/2019/documents/chiba_corona_data.xlsx

Excelファイル『感染者数等の詳細データ』のシート名「PCR検査状況」
日付→B列
人数→E列

## スクリーンショット / Screenshot
<img width="597" alt="スクリーンショット 2020-06-07 7 58 00" src="https://user-images.githubusercontent.com/19554609/83956071-fb1f9a80-a894-11ea-8e32-d5cfa556275a.png">

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kozayupapa** [comment]
対応中です

**Comment by kozayupapa** [comment]
@MiyukiShirasawa 
実施数ですが、totalだけでなく下記のように陽性、陰性で分けて表示したほうが見やすいかと思ったのですがこちらでも問題ないでしょうか？
<img width="662" alt="スクリーンショット 2020-06-18 7 48 37" src="https://user-images.githubusercontent.com/3196383/84958431-5294f480-b138-11ea-8086-997f375b20e8.png">

![image](https://user-images.githubusercontent.com/3196383/84958513-79ebc180-b138-11ea-8478-cafec6ec1cc8.png)

**Comment by MiyukiShirasawa** [comment]
@kozayupapa いいと思いますー！
