### ISSUE TITLE
検査陽性者の状況のグラフを改善する

### ISSUE THREAD

**Issue by yamanoku** [civictechzenchiba/covid19-chiba#393]
## 改善詳細 / Improve details
グラフ幅の関係で内容が見づらくなってきたのと、改行に至ってはv-htmlで`br`を挟んでいるのでコードとしては正直不健全な感じがする。

## スクリーンショット / Screenshot

[![Screenshot from Gyazo](https://gyazo.com/b2503eef7ea9a5b63f1a2d916bc9b9e1/raw)](https://gyazo.com/b2503eef7ea9a5b63f1a2d916bc9b9e1)

## 期待する見せ方・挙動 / Expected behavior
東京都のが参考になりそう。
<img width="426" alt="Screen Shot 2020-06-07 at 14 22 27" src="https://user-images.githubusercontent.com/1996642/83961043-68015780-a8ca-11ea-9bb1-0c7924aa43ca.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MiyukiShirasawa** [comment]
確認できたのでCloseします🙇‍♀️
https://deploy-preview-396--development-civictechzenchiba-covid19.netlify.app/
