### ISSUE TITLE
陽性患者の属性 カードの非表示

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#400]
## 改善詳細 / Improve details
-陽性患者の属性のデータの形式変更があり、表示が不可になったのでカードの表示を消したい

## スクリーンショット / Screenshot
<img width="1440" alt="スクリーンショット 2020-06-15 10 34 19" src="https://user-images.githubusercontent.com/19554609/84610019-20935080-aef4-11ea-93e7-904cb965bca7.png">

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamanoku** [comment]
やりますー
