### ISSUE TITLE
感染者データ処理の自動化

### ISSUE THREAD

**Issue by resessh** [civictechzenchiba/covid19-chiba#41]
# 前提
- 感染者データからdata.jsonを作るスクリプトを人力で回すのは俗人化するし大変なので自動化する
- 感染者データは白澤さんが直接メールなどで各機関からもらって、google driveに置いている
- 各機関がオープンデータとして公開webサイトに置くのはすぐには難しいそう
- 新規データがdriveに追加されたら自動処理を走らせるのが良さそう

# やること
- [ ] driveのディレクトリ構成を整理し、適切な共有設定をかける
- [ ] データを取ったり保存するバッチ処理を作る relates #8 
- [ ] Github actionsのscheduled workflowで定期的にバッチを回して変更あればPR出すようにする relates #23

**Comment by smellman** [comment]
driveからwgetするにはファイルのIDが必要となる。
ファイルのIDは新しいファイルでは変わってしまうので、メタデータ用のGoogle Spreadsheetを作ってファイルを更新とともにSpreadsheetを一緒に更新してもらうと可能になるのではないか？

- https://qiita.com/namakemono/items/c963e75e0af3f7eed732

**Comment by nekakoshi** [comment]
SpreadSheetのScriptからのデータ取得とかですかね
http://bashalog.c-brains.jp/18/09/05-113000.php

**Comment by smellman** [comment]
はい、その作戦です。
元ネタとなるGoogle SpreadSheet(Excelではない)があれば対応できそうという感じです。

**Comment by MiyukiShirasawa** [comment]
私が、Excelをメールでもらう->GoogleSpredSeetに転記する（どちらにしてもメールでもらうことは変わらなそうなので）という方法がいいですかね。

**Comment by MiyukiShirasawa** [comment]
要件が少し細かくなったのでこちらはCloseしますー
