### ISSUE TITLE
検査陽性者の状況の「現在の感染者」と「軽症・中等症」の人数が千葉県のページと異なる

### ISSUE THREAD

**Issue by AstroTaka** [civictechzenchiba/covid19-chiba#413]
検査陽性者の状況の人数について以下の千葉県のページと見比べると
「その他」の数が入っていないため「現在の感染者」と「軽症・中等症」
の人数がその分少なくなっているように見えます。

https://www.pref.chiba.lg.jp/shippei/press/2019/ncov-index.html

千葉県のサイトの集計が正しいとすると以下の様にindex.vueに
"data.other_count"を追加する必要があると思います。

    const formattedData = {
      検査実施人数: data.inspections_total_count,
      陽性患者: data.patients_count,
      現在の感染者:
        data.hospital_count +
        data.hospital_waiting_count +
        data.hotel_stay_count +
        data.home_stay_count +
        data.other_count,
      軽症中等症:
        data.hospital_count +
        data.hospital_waiting_count +
        data.hotel_stay_count +
        data.home_stay_count +
        data.other_count -
        data.severe_injury_count,

**Comment by yamanoku** [comment]
@AstroTaka こちら対応しました。指摘ありがとうございます

**Comment by AstroTaka** [comment]
ご対応ありがとうございます。
