### ISSUE TITLE
Data by：に千葉市を追加

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba#65]
## 改善詳細 / Improve details
- 千葉市のリンクを千葉市（https://www.city.chiba.jp/hokenfukushi/kenkou/kikaku/kansensyoujyouhou.html）
で追加

## スクリーンショット / Screenshot
<img width="257" alt="スクリーンショット 2020-03-17 21 20 36" src="https://user-images.githubusercontent.com/19554609/76855921-804a7300-6895-11ea-938d-32733acfcc5b.png">

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamanoku** [comment]
対応します
