### ISSUE TITLE
さくらに本番環境を作成する

### ISSUE THREAD

**Issue by resessh** [civictechzenchiba/covid19-chiba#68]
さくらのクラウドに本番環境を作る。

# 構成
![memo](https://user-images.githubusercontent.com/1481277/76879254-5efb7e00-68b9-11ea-8897-0bf656bb621e.png)

**Comment by resessh** [comment]
作業ログ
https://civictechzenchiba.slack.com/archives/CV9CGAWKY/p1584462007338900

**Comment by MiyukiShirasawa** [comment]
さくらでの環境設定完了です！！

**Comment by MiyukiShirasawa** [comment]
簡易監視設定済

**Comment by resessh** [comment]
自動デプロイについては https://github.com/civictechzenchiba/covid19-chiba/issues/93 にissueを分割したのでcloseする
