### ISSUE TITLE
現状共有されているタスクリスト

### ISSUE THREAD

**Issue by nekakoshi** [civictechzenchiba/covid19-chiba#7]
- [x] WEBページ上に書かれている「東京都」固有の情報、キーワードを「千葉県」の情報、キーワードに書き換える。
- [x] 画面に表示されているカード（検査陽性者の状況、陽性患者数、陽性患者の属性…etc）を千葉県のデータ、レイアウトに変更する
- [x]  県庁がオープンデータとして公開するExcelを、サイトで読み込める形式（json）に変換する
- [x] 画面左のメニューバーに記載するリンクを千葉県用に書き換える
- [x] GoogleAnalyticsが設定されていない？(本家tokyo)
- [x] Spreadシートから動的にデータを取得する？
- [x] 新規グラフを作成する？ (千葉ならではの情報からのグラフ化)
- [x] 現状のサイトマップ(どこページがあるか不明)
- [x] Chiba版のサイト公開(sakura? xserver? netlify? )
- [x] ロゴ決め（チーバくん使う？CHIBAロゴ使う？県章？
- [x] カラー決め
- [x] 「東京都新型コロナウィルス 対策サイト」のデザイン変更

Slack参照
- https://civictechzenchiba.slack.com/archives/CV9CGAWKY/p1584080260012300
- https://civictechzenchiba.slack.com/archives/CV9CGAWKY/p1584166896087800?thread_ts=1584166878.087300&cid=CV9CGAWKY

**Comment by smellman** [comment]
- 県庁がオープンデータとして公開するExcelを、サイトで読み込める形式（json）に変換する #8
起票しました。

**Comment by resessh** [comment]
こちらのslackってどのようにしたら参加できますか？

**Comment by yamanoku** [comment]
- WEBページ上に書かれている「東京都」固有の情報、キーワードを「千葉県」の情報、キーワードに書き換える。 #9 起票しました

**Comment by yamanoku** [comment]
@MiyukiShirasawa @nekakoshi 本Issue、Pin留めしておくと良いかもです

**Comment by K2nori** [comment]
質問になってしまうのですが、isuuesの中を見ても、pages/about.vueの中に東京の文言、電話番号のテキストが残っていると思います。これも対応案件ですよね？そこまで細かくIssueは立てていないのでしょうか？使い慣れていない中で、何か少しでもお役に立てればと。

**Comment by K2nori** [comment]
> 質問になってしまうのですが、isuuesの中を見ても、pages/about.vueの中に東京の文言、電話番号のテキストが残っていると思います。これも対応案件ですよね？そこまで細かくIssueは立てていないのでしょうか？使い慣れていない中で、何か少しでもお役に立てればと。

上記、masterでは直っていることが確認できました。

**Comment by nekakoshi** [comment]
掲載されていたタスクが全て完了したようなので、
こちらはクローズします。
改修点が出てきましたら新規Issuesで掲載お願いします。
