### ISSUE TITLE
makerelの追加とslack通知追加

### ISSUE THREAD

**Issue by nekakoshi** [civictechzenchiba/covid19-chiba#80]
## 改善詳細 / Improve details
- サーバの監視を行うためにmakerelの追加をお願いします。
- makerelのアカウント作成お願いします。(@MiyukiShirasawa )
 https://mackerel.io/ja/docs/entry/getting-started

## 期待する見せ方・挙動 / Expected behavior
- サーバリソースの確認
- 利用サービスのプロセスの確認

## 動作環境・ブラウザ / Environment
- nothing

## 参考
- mekerelの追加
  https://mackerel.io/ja/docs/entry/howto/install-agent/deb

- makerelのSlack通知
  https://mackerel.io/ja/docs/entry/howto/alerts/slack

- h2oサーバの監視
  https://soudai.hatenablog.com/entry/mackerel-plugin-h2o

- 外形監視 (domain.com/ でよいかと)
  https://mackerel.io/ja/docs/entry/external-monitoring

**Comment by resessh** [comment]
さくらのシンプル監視を設定しました
